version: 2.1

yaml_anchors:
  build_one: &build_one
    steps:
      - checkout
      - run: docker login -u=$DOCKER_HUB_USERNAME -p=$DOCKER_HUB_PASSWORD
      - run: echo "export DOCKER_ARCHITECTURE=$(dpkg --print-architecture)" >> $BASH_ENV
      - run: printf ${DOCKER_ARCHITECTURE}
      - run: echo "export DOCKER_IMAGE=codingbadly/multi-arch-fuff:${DOCKER_ARCHITECTURE}" >> $BASH_ENV
      - run: printf ${DOCKER_IMAGE}
      - run: docker build --force-rm -t codingbadly/multi-arch-fuff:$(dpkg --print-architecture) .
      - run: docker image inspect codingbadly/multi-arch-fuff:$(dpkg --print-architecture) | grep "Architecture"
      - run: echo "export DOCKER_TAG=$(docker run -it --rm --entrypoint /bin/sh codingbadly/multi-arch-fuff -c 'printf $RUST_VERSION')" >> $BASH_ENV
      - run: printf ${DOCKER_TAG}
      - run: docker push codingbadly/multi-arch-fuff:$(dpkg --print-architecture)

jobs:
  build_arm64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    <<: *build_one
#    steps:
#      - checkout
#      - run: docker login -u=$DOCKER_HUB_USERNAME -p=$DOCKER_HUB_PASSWORD
#      - run: docker build --force-rm -t codingbadly/multi-arch-fuff:manifest-$(dpkg --print-architecture) .
#      - run: docker image inspect codingbadly/multi-arch-fuff:manifest-$(dpkg --print-architecture) | grep "Architecture"

  build_amd64:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    <<: *build_one
#    steps:
#      - checkout
#      - run: docker login -u=$DOCKER_HUB_USERNAME -p=$DOCKER_HUB_PASSWORD
#      - run: docker build --force-rm -t codingbadly/multi-arch-fuff:manifest-$(dpkg --print-architecture) .
#      - run: docker image inspect codingbadly/multi-arch-fuff:manifest-$(dpkg --print-architecture) | grep "Architecture"

  build_manifest:
    machine:
      image: ubuntu-2004:current
    resource_class: small
    steps:
      - run: docker login -u=$DOCKER_HUB_USERNAME -p=$DOCKER_HUB_PASSWORD
      - run: docker manifest create codingbadly/multi-arch-fuff:latest >
          --amend codingbadly/multi-arch-fuff:arm64
          --amend codingbadly/multi-arch-fuff:amd64
      - run: docker manifest push codingbadly/multi-arch-fuff:latest

workflows:
  build_all:
    jobs:
      - build_arm64:
          context:
            - docker-hub
      - build_amd64:
          context:
            - docker-hub
      - build_manifest:
          context:
            - docker-hub
          requires:
            - build_arm64
            - build_amd64
