version: 2.1

jobs:
  build_arm64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - docker build --force-rm -t codingbadly/multi-arch-fuff:manifest-$(dpkg --print-architecture) .
      - docker image inspect codingbadly/multi-arch-fuff:manifest-$(dpkg --print-architecture) | grep "Architecture"

#  build_amd64:
#    steps:
#      - checkout

workflows:
  build_all:
    jobs:
      - build_arm64
#      - build_amd64
