version: 2.1

yaml_anchors:
  build_one: &build_one
    steps:
      - checkout
      - run: docker login -u=$DOCKER_HUB_USERNAME -p=$DOCKER_HUB_PASSWORD
      - run: docker build --force-rm -t multi-arch-fuff-stage .
      - run: docker image inspect multi-arch-fuff-stage | grep "Architecture"
      - run: echo "export TARGET_ARCHITECTURE=$(dpkg --print-architecture)" >> $BASH_ENV
      - run: printf "\n>%s<\n\n" ${TARGET_ARCHITECTURE}
      - run: echo "export RUST_VERSION=$(docker run -it --rm --entrypoint /bin/sh multi-arch-fuff-stage -c 'printf $RUST_VERSION')" >> $BASH_ENV
      - run: printf "\n>%s<\n\n" ${RUST_VERSION}
      - run: echo "export DOCKER_IMAGE_1=codingbadly/multi-arch-fuff:${RUST_VERSION}-${TARGET_ARCHITECTURE}" >> $BASH_ENV
      - run: printf "\n>%s<\n\n" ${DOCKER_IMAGE_1}
      - run: echo "export DOCKER_IMAGE_2=codingbadly/multi-arch-fuff:latest-${TARGET_ARCHITECTURE}" >> $BASH_ENV
      - run: printf "\n>%s<\n\n" ${DOCKER_IMAGE_2}
      - run: docker tag multi-arch-fuff-stage ${DOCKER_IMAGE_1}
      - run: docker tag multi-arch-fuff-stage ${DOCKER_IMAGE_2}
      - run: docker push ${DOCKER_IMAGE_1}
      - run: docker push ${DOCKER_IMAGE_2}

jobs:
  build_arm64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    <<: *build_one

  build_amd64:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    <<: *build_one

#  build_manifest:
#    machine:
#      image: ubuntu-2004:current
#    resource_class: small
#    steps:
#      - run: docker login -u=$DOCKER_HUB_USERNAME -p=$DOCKER_HUB_PASSWORD
#      - run: docker manifest create codingbadly/multi-arch-fuff:latest >
#          --amend codingbadly/multi-arch-fuff:arm64
#          --amend codingbadly/multi-arch-fuff:amd64
#      - run: docker manifest push codingbadly/multi-arch-fuff:latest

workflows:
  build_all:
    jobs:
      - build_arm64:
          context:
            - docker-hub
      - build_amd64:
          context:
            - docker-hub
#      - build_manifest:
#          context:
#            - docker-hub
#          requires:
#            - build_arm64
#            - build_amd64
